## **Machine Learning Project**:

**The Problem Statement for the Project is:**

Let us assume there is a Hobby Botanist. She is working on distinguishing various flowers. She had made 4 labels for each flower which will help her to categorize the flowers.This categorizaton is made on the basis of length and width of sepals and petals. An entire database has been created by her. She has contacted her botanist friends across the globe and told them the way to categorize the flowers. These botanists then went out in the real world and took pictures of different flowers and measured the length and width of sepals and petals. They created an entire database by their own domain knowledge and labelled it. Now what happens is the botanist approached us for our expert help in building a machine learning model that can learn from the measurements of these irises contained in the dataset. So basically our machine learning model can learn from that dataset and predict the species or 4 different categories of any new flower. 

**Basic Purpose of making such type of ML model is:**

When any unknown flower is brought to you so your machine learning model can predict based on length and width of petals and sepals the species of flower. So what will be the use of such machine learning model? So it will be useful for many volunteers from around the globe who are new to the world of botany can go out in real world and measure the length and width of sepals and petals with help of normal scale and predict which species of flower is that. 

So here I will first import some libraries important for the project:



In [3]:
import pandas as pd
import numpy as np


Now I will explore the dataset required for the project that is iris dataset provided by the botanist. I will make use of scikit-learn.


In [4]:
from sklearn.datasets import load_iris
iris_dataset = load_iris() 
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))


Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


The DESCR keyword is used to give a short description of dataset.

In [5]:
print(iris_dataset['DESCR'][:200] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


The value of target names provides the actual values of the flowers that I want to predict. i.e. sentosa, versicolor,etc. So I have printed it here as well from the iris dataset.

In [6]:
print("Target Names: \n{}".format(iris_dataset['target_names']))

Target Names: 
['setosa' 'versicolor' 'virginica']


Then comes the feature names it provides the features that the flowers are having such as sepal and petal length and width. It is printed as well from the iris dataset as shown.

In [7]:
print("Features Names: \n{}".format(iris_dataset['feature_names']))

Features Names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Then the next key value is the type of data which shows us whether the data is a type of list, or ndarray. So I can print the type of data from iris dataset as shown below.

In [8]:
print("Type of Data: \n{}".format(type(iris_dataset['data'])))

Type of Data: 
<class 'numpy.ndarray'>


Then the another key value in dataset is shape of data. This will display us the measurements for the different flowers present in dataset with its features. It can be printed from iris dataset as shown.

In [9]:
print("Shape of Data: \n{}".format(iris_dataset['data'].shape))

Shape of Data: 
(150, 4)


Now as some of the key values are known I can print the first five rows of the iris dataset and see what output it gives us.It can be printed as shown below.

In [10]:
print("First five rows of data: \n{}".format(iris_dataset['data'][:5]))

First five rows of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


As I can see it prints out the measurements of sepals and petals width and length. Now next key value is the target. I will first find the type of target as shown below.


In [11]:
print("Type of target: \n{}".format(type(iris_dataset['target'])))

Type of target: 
<class 'numpy.ndarray'>


As I can see the type of target is ndarray. Now I move on to see the shape of target. It can be printed from dataset as shown below.

In [12]:
print("Shape of target: \n{}".format(iris_dataset['target'].shape))

Shape of target: 
(150,)


As the target is a one-dimensional array, and on seeing the shape I can see that it contains one entry per flower. So next I move to the target field and print the target as shown below. 

In [13]:
print("Target: \n{}".format(iris_dataset['target']))

Target: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


The meaning of the numbers such as 0,1,2 indicate the names of the flowers. 0 is for setosa, 1 is for versicolor and 2 is for virginica.

Now as our dataset is ready I will now train our machine learning model by giving values to learn. So I will provide 75% rows of the dataset to the model for learning and remaining 25% I will keep it as a test data. I will create X_train, X_test, y_train, y_test as shown.

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

Now as the dataset is give to the machine learning model to get trained, I am now able to determine the type of data which is trained as shown.

In [15]:
print("X_train shape:{}". format(X_train.shape))
print("y_train shape:{}". format(y_train.shape))
print("X_test shape:{}". format(X_test.shape))
print("y_test shape:{}". format(y_test.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(38, 4)
y_test shape:(38,)


Now I will actual train the machine learning model. I will make use of k-nearest classification algorithm. It is used in the model as KNeighborsClassifier class as neighbors module.Before I use it I will instantiate the class into an object as shown below.

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)


Now the knn object will encapsulate the algorithm that will be used to build the model from the training data, as well as algorithm to make predictions on new data points. To build model on training set, I will need to call the fit method of knn object, such as X_train and y_train as shown below.

In [17]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Now I can start to make predictions using this model on new data for which I might not know the correct labels. So now I am going to provide some new values such as sepal and petal length and width for unknown flower.

In [24]:
X_new = np.array([[5.2,9,1,0.2]])
print("X_new.shape: {}". format(X_new.shape))

X_new.shape: (1, 4)


Now that I have made the measurements of this single flower in a row of two-dimensional Numpy array, I am now going to make the predictions.

In [23]:
prediction = knn.predict(X_new)
print("Prediction:{}". format(prediction))
print("Predicted target name: {}". format(
iris_dataset['target_names'][prediction]))

Prediction:[0]
Predicted target name: ['setosa']


The whole point of building this model is that I dont know the correct species of the sample, so how we can verify? So here comes the test set that I created earlier. It is not used to build the model but to test the model that it has trained completely or not.

In [20]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}". format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [21]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158


As we can see our accuracy is 0.9736 percentage so our model is accurate enough to predict the species of any unknown flower.